### ISSUE TITLE
SGP41 in DMA mode

### ISSUE THREAD

**Issue by remyhx** [Sensirion/embedded-i2c-sgp40#4]
Hi. For polling we use two bytes for the address/command and six for the humidity/temperature/crc input. Is it also possible to work with only a 16-bit address/command, so I could use DMA readout to avoid too much processor work? (The algorithm should be fed with a 1 second readout.)

**Comment by LeonieFierz** [comment]
Hi @remyhx

The measure command always needs the humidity/temperature/crc to be set. If compensation is not needed, you can send the fixed default values, but still the bytes need to be sent.

Best regards, Léonie
